/** Full funeral package catalog from pompe-funebrebucuresti.ro (talon pensie pricing). */

export type FuneralPackage = {
  id: string;
  name: string;
  priceLabel: string;
  kind: "inhumare" | "incinerare";
  image: string;
  services: string[];
  products: string[];
  preview: string[];
};

// Package photos are self-hosted in /public/images/packages, ordered 1 to 8 plus the urn
const img1 = "/images/packages/1-funer.jpg";
const img2 = "/images/packages/2-funer.jpg";
const img3 = "/images/packages/3-funer.jpg";
const img4 = "/images/packages/4-funer.jpg";
const img5 = "/images/packages/5-funer.jpg";
const img6 = "/images/packages/6-funer.jpg";
const img7 = "/images/packages/7-funer.jpg";
const img8 = "/images/packages/8-funer.jpg";
const imgUrna = "/images/packages/urna-funer.jpg";

/** Shared core services for înhumare / incinerare packages. */
const coreServices = [
  "Constatare deces",
  "Îmbălsamare decedat",
  "Acte necesare: certificat constatator, certificat îmbălsamare, certificat deces, adeverință înhumare",
  "Toaletare (spălat / îmbrăcat)",
  "Transport sicriu la domiciliu",
  "Așezarea decedatului în sicriu",
  "Transport funerar (biserică / cimitir)",
  "Manipulare (decedat / sicriu)",
  "Acte aduse la domiciliu",
  "Dosar ajutor înmormântare",
];

const sicriuBaza = [
  "Sicriu complet echipat: capitonaj capac, lenjerie (respeta), pernă, saltea, voal, orar (mare și mic), crucifix, cruce lemn înscripționată",
];

const sicriuComplet = [
  "Sicriu complet echipat: capitonaj capac, lenjerie (respeta), pernă, saltea, voal, orar (mare și mic), crucifix, mânere 4 buc, șuruburi capac 8 buc, cruce lemn înscripționată",
];

/** All 9 packages in the order shown on the old homepage. */
export const packages: FuneralPackage[] = [
  {
    id: "inhumare-0",
    name: "Pachet înhumare 0 Ron cu talonul de pensie",
    priceLabel: "0 Ron",
    kind: "inhumare",
    image: img1,
    services: coreServices,
    products: [
      ...sicriuBaza,
      "12 Batiste",
      "12 Lumânări mici",
      "12 Bănuți",
      "12 Doliu piept",
      "1 Iconiță sfințită",
      "2 Prosoape mari",
      "2 Lumânări mari",
      "6 Prosoape mici",
      "2 Platouri colivă",
      "12 Pachete produse (dulce/post)",
      "1 Sticlă vin · 1 Sticlă vin+ulei",
      "1 Set pahare / lingurițe plastic",
      "15 Lumânări",
      "3 Colaci",
    ],
    preview: [
      "Sicriu complet echipat",
      "Toate actele și transportul",
      "Pomană de bază inclusă",
      "0 Ron cu talon pensie",
    ],
  },
  {
    id: "inhumare-900",
    name: "Pachet înhumare 900 Ron cu talonul de pensie",
    priceLabel: "900 Ron",
    kind: "inhumare",
    image: img2,
    services: coreServices,
    products: [
      ...sicriuComplet,
      "12 Batiste",
      "12 Bănuți",
      "12 Doliu piept",
      "1 Iconiță sfințită",
      "2 Prosoape mari",
      "2 Lumânări mari",
      "6 Prosoape mici",
      "1 Coroană garoafe (70 flori)",
      "12 Batiste cu lumânare și bănuț",
      "12 Vase",
      "12 Căni",
      "12 Furculițe",
      "12 Porții mâncare gătită",
      "12 Produse (dulce/post) la fiecare vas",
      "10 Prosoape mici",
      "2 Platouri colivă",
      "3 Colaci",
      "1 Sticlă vin",
      "1 Sticlă vin+ulei",
      "1 Set pahare / lingurițe plastic",
      "15 Lumânări",
    ],
    preview: [
      "Sicriu cu mânere",
      "Coroană garoafe",
      "Pomană cu mâncare gătită",
      "900 Ron cu talon pensie",
    ],
  },
  {
    id: "inhumare-1300",
    name: "Pachet înhumare 1300 Ron cu talonul de pensie",
    priceLabel: "1.300 Ron",
    kind: "inhumare",
    image: img3,
    services: coreServices,
    products: [
      ...sicriuComplet,
      "12 Batiste",
      "12 Lumânări mici",
      "12 Bănuți",
      "12 Doliu piept",
      "1 Iconiță sfințită",
      "2 Prosoape mari",
      "2 Lumânări mari",
      "6 Prosoape mici",
      "2 Platouri colivă",
      "12 Pachete produse (dulce/post)",
      "1 Sticlă vin",
      "1 Sticlă vin+ulei",
      "1 Set pahare / lingurițe plastic",
      "15 Lumânări",
      "3 Colaci",
    ],
    preview: [
      "Sicriu complet echipat",
      "Acte + transport",
      "Pachete pomană",
      "1.300 Ron cu talon pensie",
    ],
  },
  {
    id: "inhumare-1600",
    name: "Pachet înhumare 1600 Ron cu talonul de pensie",
    priceLabel: "1.600 Ron",
    kind: "inhumare",
    image: img4,
    services: coreServices,
    products: [
      ...sicriuComplet,
      "1 Coroană garoafe (70 flori)",
      "12 Batiste",
      "12 Lumânări mici",
      "12 Bănuți",
      "12 Doliu piept",
      "1 Iconiță sfințită",
      "2 Prosoape mari",
      "2 Lumânări mari",
      "6 Prosoape mici",
      "2 Platouri colivă",
      "12 Pachete produse (dulce/post)",
      "1 Sticlă vin",
      "1 Sticlă vin+ulei",
      "1 Set pahare / lingurițe plastic",
      "15 Lumânări",
      "3 Colaci",
    ],
    preview: [
      "Sicriu complet",
      "Coroană garoafe",
      "Pomană tradițională",
      "1.600 Ron cu talon pensie",
    ],
  },
  {
    id: "inhumare-1900",
    name: "Pachet înhumare 1900 Ron cu talonul de pensie",
    priceLabel: "1.900 Ron",
    kind: "inhumare",
    image: img5,
    services: coreServices,
    products: [
      ...sicriuComplet,
      "1 Coroană garoafe (70 flori)",
      "12 Batiste",
      "12 Lumânări mici",
      "12 Bănuți",
      "12 Doliu piept",
      "1 Iconiță sfințită",
      "2 Prosoape mari",
      "2 Lumânări mari",
      "6 Prosoape mici",
      "2 Platouri colivă",
      "12 Pachete produse (dulce/post)",
      "1 Sticlă vin",
      "1 Sticlă vin+ulei",
      "1 Set pahare / lingurițe plastic",
      "15 Lumânări",
      "3 Colaci",
    ],
    preview: [
      "Sicriu premium echipat",
      "Coroană garoafe",
      "Pomană completă",
      "1.900 Ron cu talon pensie",
    ],
  },
  {
    id: "inhumare-2400",
    name: "Pachet înhumare 2400 Ron cu talonul de pensie",
    priceLabel: "2.400 Ron",
    kind: "inhumare",
    image: img6,
    services: coreServices,
    products: [
      ...sicriuComplet,
      "1 Coroană garoafe (70 flori)",
      "12 Batiste cu lumânare și bănuț",
      "12 Vase",
      "12 Căni",
      "12 Furculițe",
      "12 Porții mâncare gătită",
      "12 Produse (dulce/post) la fiecare vas",
      "1 Iconiță sfințită",
      "2 Prosoape mari",
      "2 Lumânări mari",
      "10 Prosoape mici",
      "2 Platouri colivă",
      "3 Colaci",
      "12 Doliu de piept",
      "1 Sticlă vin",
      "1 Sticlă vin+ulei",
      "1 Set pahare / lingurițe plastic",
      "15 Lumânări",
    ],
    preview: [
      "Coroană + pomană cu mese",
      "12 porții mâncare",
      "Sicriu complet",
      "2.400 Ron cu talon pensie",
    ],
  },
  {
    id: "inhumare-2700",
    name: "Pachet înhumare 2700 Ron cu talonul de pensie",
    priceLabel: "2.700 Ron",
    kind: "inhumare",
    image: img7,
    services: coreServices,
    products: [
      ...sicriuComplet,
      "12 Batiste cu lumânare și bănuț",
      "12 Vase",
      "12 Căni",
      "12 Furculițe",
      "1 Coroană trandafiri (70 flori)",
      "12 Porții mâncare gătită",
      "12 Produse (dulce/post) la fiecare vas",
      "1 Iconiță sfințită",
      "2 Prosoape mari",
      "2 Lumânări mari",
      "10 Prosoape mici",
      "2 Platouri colivă",
      "3 Colaci",
      "12 Doliu de piept",
      "1 Sticlă vin",
      "1 Sticlă vin+ulei",
      "1 Set pahare / lingurițe plastic",
      "15 Lumânări",
    ],
    preview: [
      "Coroană trandafiri",
      "Pomană cu mâncare gătită",
      "Sicriu complet",
      "2.700 Ron cu talon pensie",
    ],
  },
  {
    id: "inhumare-6700",
    name: "Pachet înhumare 6700 Ron cu talonul de pensie",
    priceLabel: "6.700 Ron",
    kind: "inhumare",
    image: img8,
    services: coreServices,
    products: [
      ...sicriuComplet,
      "1 Coroană garoafe (70 flori)",
      "12 Batiste cu lumânare și bănuț",
      "12 Vase",
      "12 Căni",
      "12 Furculițe",
      "12 Porții mâncare gătită",
      "12 Produse (dulce/post) la fiecare vas",
      "1 Iconiță sfințită",
      "2 Prosoape mari",
      "2 Lumânări mari",
      "10 Prosoape mici",
      "2 Platouri colivă",
      "3 Colaci",
      "12 Doliu de piept",
      "1 Sticlă vin",
      "1 Sticlă vin+ulei",
      "1 Set pahare / lingurițe plastic",
      "15 Lumânări",
    ],
    preview: [
      "Pachet premium complet",
      "Coroană + pomană extinsă",
      "Toate serviciile incluse",
      "6.700 Ron cu talon pensie",
    ],
  },
  {
    id: "incinerare-900",
    name: "Pachet incinerare 900 Ron cu talonul de pensie",
    priceLabel: "900 Ron",
    kind: "incinerare",
    image: imgUrna,
    services: coreServices,
    products: [
      ...sicriuComplet,
      "12 Batiste",
      "12 Lumânări mici",
      "12 Bănuți",
      "12 Doliu piept",
      "1 Coroană garoafe",
    ],
    preview: [
      "Incinerare cu talon pensie",
      "Sicriu complet echipat",
      "Coroană garoafe",
      "900 Ron",
    ],
  },
];
